// Prisma configuration is handled through package.json
// This file is no longer used

/*
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx prisma/anotheroldseed.ts`,
    // seed:`node prisma/seed.js`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
*/
